---
title: "Output"
author: "Qian Shi (qs2164)"
date: "12/6/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(ggplot2)
library(gridExtra)
df <- data.frame(model = rep(c('xgb', 'lr', 'svm (linear)', 'gbm', 'rf', 'svm (rbf)', 'svm (poly)'), each=10),
                 class = c("air_conditioner", "car_horn", "children_playing",
                           "dog_bark", "drilling", "enginge_idling",
                           "gun_shot", "jackhammer", "siren", "street_music"),
                 #class = as.character(rep(c(0:9),5)),
                 accuracy=c(0.36,0.69,0.76,0.86,0.67,0.43,0.89,0.33,0.47,0.76,
                            0.18, 0.51, 0.56, 0.82, 0.5, 0.48, 0.66, 0.17, 0.53, 0.64,
                            0.18, 0.46, 0.80, 0.36, 0.47, 0.48, 0.49, 0.33, 0.33, 0.71,
                            0.36, 0.57, 0.73, 0.88, 0.6, 0.52, 0.74, 0.17, 0.47, 0.73,
                            0.18, 0.57, 0.73, 0.90, 0.50, 0.35, 0.83, 0.33, 0.33, 0.69,
                            0, 0, 0, 1, 0, 0, 0.03, 0, 0, 0,
                            0.27, 0.57, 0.61, 0.58, 0.37, 0.17, 0.74, 0.42, 0.4, 0.51))
df$model<- factor(df$model, levels = c('xgb', 'lr', 'svm (linear)', 'gbm', 'rf', 'svm (rbf)', 'svm (poly)'))
df$class<- factor(df$class, levels = c("air_conditioner", "car_horn", "children_playing",
                                       "dog_bark", "drilling", "enginge_idling",
                                       "gun_shot", "jackhammer", "siren", "street_music"))
```

```{r}
bar<- ggplot(data=df, aes(x=class, y=accuracy, fill=model)) +
  geom_col(position='dodge', width=0.7, alpha=0.8)+
  ggtitle("Accuracy for 10 different classes audios",
          subtitle="(with 5 different models)")+
  ylim(0, 1)+
  labs(x = "", y = "")+
  coord_flip()+
  theme_grey(11)+
  theme(legend.title = element_blank())+
  scale_fill_manual(values = c("#ee4035", "#7bc043", "#f37736", "#fcec4d", "#0392cf", "#c79ddc", "#9a8262"))+
  theme(axis.text.y = element_text(face="bold", size=9),
        plot.title = element_text(face="bold", size=14), 
        plot.subtitle = element_text(face="italic", size=10))
```

```{r}
bub<- ggplot(df, aes(x=class, y=accuracy, color=model))+
  geom_point(size=5, alpha=0.7)+
  ggtitle("Accuracy for 10 different classes audios",
          subtitle="(with 5 different models)")+
  ylim(0, 1)+
  labs(x = "", y = "")+
  coord_flip()+
  scale_color_manual(values = c("#ee4035", "#7bc043", "#f37736", "#fcec4d", "#0392cf", "#c79ddc", "#9a8262"))+
  theme_grey(11)+
  theme(legend.title=element_blank())+
  theme(axis.text.y = element_text(face="bold", size=9),
        plot.title = element_text(face="bold", size=14), 
        plot.subtitle = element_text(face="italic", size=10))
```

```{r, fig.height=4, fig.width=8}
grid.arrange(bar, bub, ncol=2)
```

